{% if version is not defined %}
{% set version = "3.9" %}
{% endif %}

package:
  name: python-abi3-split
  version: {{ version }}

build:
  number: 0

outputs:
  - name: python-abi3
    build:
      noarch: generic
      run_exports:
        - _python_abi3_support 1.*
        - python >={{ version }}
      script_env:
        - PY_LIMITED_API={{ version_hex }}
    requirements:
      build:
        - sed      # [unix]
        - m2-sed   # [win]
      host:
      run:
        - python {{ version }}
        - _python_abi3_support
        - __unix   # [unix]
        - __win    # [win]
    test:
      commands:
        - echo "hello world!"

  - name: _python_abi3_support
    version: 1.0
    build:
      noarch: generic
    requirements:
      run:
        - cpython
        - python-gil
    test:
      commands:
        - echo "hello world!"

about:
  home: https://github.com/conda-forge/python-abi3-feedstock
  summary: 'Support Python ABI3 packages on conda'
  description: |
    python-abi3 package can be used for supporting ABI3 packages on
    conda-forge. ABI3 supports building a C extension for one specific
    CPython version and make it work on any later version.
    (freethreading is not supported)
  license: MIT
  license_file: LICENSE.txt

extra:
  feedstock-name: python-abi3
  recipe-maintainers:
    - isuruf
